In [7]:
import pandas as pd 
import numpy as np

In [11]:
fraud_data = pd.read_csv("./fraud_detect.csv")
fraud_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
153753,99980,-0.460128,0.203036,0.469998,-0.877349,-0.333565,1.198391,1.088143,-0.303794,2.153779,...,0.006073,0.674304,-0.172643,-1.395636,-1.057282,0.487519,-0.252142,-0.041332,224.73,0
153754,99984,1.930509,0.589877,-0.573178,4.011452,0.646176,0.406016,0.003458,-0.104042,0.606845,...,-0.084729,0.160308,0.110852,0.603596,0.152945,0.028829,-0.056768,-0.050443,7.55,0
153755,99995,-0.080563,0.840885,-0.085326,-0.606702,0.879790,-0.493156,0.879652,-0.217802,1.515205,...,-0.479545,-1.013772,0.061588,-1.097930,-0.392758,0.157989,0.095614,0.062466,18.69,0
153756,99998,-1.730665,1.302833,0.397864,-0.445631,-0.773382,0.223966,-0.921886,1.329246,0.899559,...,0.370008,0.921796,-0.118298,0.797808,-0.386084,0.463457,-0.517093,-0.076129,29.90,0
153757,99999,-0.309641,0.771215,0.679051,-1.069673,1.414042,-0.379638,1.315839,-0.449971,1.162826,...,-0.463374,-0.943621,-0.200362,-1.129995,-0.170943,0.087432,-0.149035,-0.106371,19.17,0

In [17]:
# fraud_data.head()
# fraud_data.tail()
# fraud_data.shape
# fraud_data.info()
# fraud_data.isnull().sum()
fraud_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,...,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000,153758.000000
mean,55219.166333,-0.234187,0.045504,0.604016,0.134835,-0.236612,0.069428,-0.103249,0.051217,-0.029171,...,-0.036877,-0.109254,-0.028362,0.011553,0.115682,0.022757,0.001876,0.002859,88.537235,0.002146
std,22658.988461,1.836892,1.620692,1.327202,1.352793,1.326851,1.290105,1.195012,1.239475,1.131997,...,0.742079,0.647129,0.585021,0.595752,0.448905,0.490984,0.392118,0.311831,246.097358,0.046278
min,0.000000,-56.407510,-72.715728,-33.680984,-5.519697,-42.147898,-26.160506,-31.764946,-73.216718,-9.462573,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-11.710896,0.000000,0.000000
25%,39394.000000,-1.021436,-0.539477,0.096945,-0.723555,-0.873953,-0.675633,-0.598162,-0.143827,-0.685397,...,-0.229086,-0.551681,-0.170680,-0.327445,-0.159352,-0.325815,-0.062807,-0.009576,5.860000,0.000000
50%,56784.000000,-0.258642,0.119851,0.704860,0.154723,-0.278833,-0.187899,-0.050370,0.072529,-0.116185,...,-0.059646,-0.085381,-0.041720,0.065159,0.154804,-0.056037,0.011011,0.022910,22.505000,0.000000
75%,73829.000000,1.164805,0.805848,1.337165,0.975383,0.295161,0.457292,0.435721,0.368644,0.571993,...,0.115133,0.321049,0.088913,0.411360,0.413009,0.286990,0.089884,0.078260,79.000000,0.000000
max,99999.000000,2.401777,18.902453,9.382558,16.875344,34.801666,22.529298,36.677268,20.007208,15.594995,...,27.202839,10.503090,19.002942,4.022866,7.519589,3.517346,12.152401,33.847808,19656.530000,1.000000

In [21]:
class_names = {0:"Not Fraud", 1:"Fraud"}
print(fraud_data.Class.value_counts().rename(index=class_names))

Not Fraud    153428
Fraud           330
Name: Class, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

y = fraud_data["Class"]

x = fraud_data.loc[:, fraud_data.columns != "Class"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=1/3, random_state=42, stratify=y)

x_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
32096,36636,-0.556476,0.763791,1.526293,-1.338977,0.055728,-0.601567,0.681059,-0.143321,0.366432,...,0.203522,-0.156812,-0.102191,-0.030903,0.124942,-0.286211,0.727246,0.141696,-0.097933,7.68
40165,40122,-2.280471,-0.326044,0.244870,1.118990,0.262526,-0.612519,1.051707,0.301572,-0.993480,...,-0.194594,-0.330055,-0.612499,1.475323,-0.099025,0.160107,-0.588166,0.387752,-0.079526,199.90
20310,30943,-0.517172,0.384920,2.014336,1.247855,-0.306978,0.337996,0.079046,0.296088,0.218632,...,0.015205,0.258817,0.859568,-0.059669,0.071208,-0.300359,-0.157647,0.197853,0.162837,47.80
103907,68847,1.275845,-0.890244,-1.740971,-1.759315,1.725460,2.937240,-0.491588,0.602610,-1.282300,...,0.417372,-0.129422,-0.904907,-0.063096,0.992000,0.570146,-0.447815,-0.041373,0.023436,125.15
95791,65468,-0.280641,1.064322,1.677338,0.153278,-0.090096,-1.260371,0.915463,-0.322169,-0.273264,...,0.159370,-0.282315,-0.570511,0.008598,0.865049,-0.261254,0.010732,0.082948,-0.119656,1.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95679,65419,-0.144034,1.223659,-0.255421,1.314053,0.290211,-0.678083,0.544573,0.250660,-0.878896,...,0.074420,0.225462,0.754134,0.167102,0.115438,-0.713587,-0.323169,0.292775,0.087152,22.24
93185,64285,0.997774,-0.618597,1.268644,1.401820,-0.592760,1.982795,-1.162782,0.664184,1.502888,...,-0.051910,-0.036956,0.308709,-0.264624,-1.089620,0.596984,-0.145649,0.112083,0.021608,54.89
33495,37256,-2.528657,-0.343713,2.552338,2.265170,5.936980,-4.013499,-6.140718,-0.721761,0.489934,...,-1.271693,0.581498,-2.065646,-9.587483,0.877383,-2.729109,-0.640681,0.280202,0.406317,18.75
58280,48319,1.470151,-0.432102,-0.539163,-0.956843,-0.277923,-0.639283,-0.232350,-0.143694,-1.176314,...,0.019397,0.171971,0.350472,-0.261815,-0.486822,0.834439,-0.046598,-0.040733,-0.019838,10.00
74264,55495,1.268762,0.151264,-0.013182,-0.119725,-0.085258,-0.832852,0.260397,-0.266134,-0.121395,...,-0.023431,-0.040880,-0.003052,-0.018060,0.194447,0.392159,1.065891,-0.079687,-0.005022,8.34

In [34]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

logisreg = LogisticRegression(max_iter = 1000)
logisreg.fit(x_train, y_train)
y_pred = logisreg.predict(x_test)
acc_logisreg = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy", acc_logisreg)

Accuracy 99.88

In [35]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc_ganb = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy", acc_ganb)

Accuracy 98.54

In [41]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc_dtree = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy", acc_dtree)

Accuracy 99.9

In [63]:
from sklearn.ensemble import RandomForestClassifier

randomForest = RandomForestClassifier()
randomForest.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc_rf = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy", acc_rf)

Accuracy 99.8

In [50]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc_km = round(accuracy_score(y_test, y_pred)*100,2)
print("Accuracy", acc_km)

Accuracy 99.8

In [62]:
models = pd.DataFrame({
    'Model':['Logistic Regress', 'Naive Bayes', 'Decision Tree', 'Random Forest', 'K-Nearest Neighbors'],
    'Score':[acc_logisreg,acc_ganb,acc_dtree,acc_rf,acc_km]
})

models.sort_values(by='Score',ascending=False)

                 Model  Score
2        Decision Tree  99.90
0     Logistic Regress  99.88
3        Random Forest  99.80
4  K-Nearest Neighbors  99.80
1          Naive Bayes  98.54